### ISSUE TITLE
DataSet Problem

### ISSUE THREAD

**Issue by Fortuneteller6** [Linaom1214/U-Transformer#3]
In the data folder, the tarin2022.txt is same as the test2022.txt? Also why put a zero in the end of each coordinate?

**Comment by Linaom1214** [comment]
> In the data folder, the tarin2022.txt is same as the test2022.txt? Also why put a zero in the end of each coordinate?

“0” is the class for object. the train2022.txt is not same as test2022.txt. 
you can write a script to split the train and test num. (the 'script' means convert the orign labels to this method, the files which train or test should be confirm when you run the convert 'script')

**Comment by Fortuneteller6** [comment]
> > In the data folder, the tarin2022.txt is same as the test2022.txt? Also why put a zero in the end of each coordinate?
> 
> “0” is the class for object. the train2022.txt is not same as test2022.txt. you can write a script to split the train and test num.

I mean the test2022.txt you provided is the same as the train2022.txt? Another issue is whether random shuffling was used when creating txt files?

**Comment by Linaom1214** [comment]
> Author

Yes, the content type in two files is same.  
The train and test files are fixed, don't random shuffle.

**Comment by Fortuneteller6** [comment]
> > Author
> 
> Yes, the content type in two files is same. The train and test files are fixed, don't random shuffle.

I have sent an email to your address, Could u take some time to check it. Thanks.
